report:
  description: Run watchman report
  fields:
    create_file:
      example: true
      default: true
      required: false
      selector:
        boolean:
    action:
      example: "persistent_notification.create"
      required: false
      selector:
        text:
    data:
      example: "title: Watchman Report"

    parse_config:
      example: true
      default: false
      required: false
      selector:
        boolean:
    chunk_size:
      example: 3500
      default: 3500
      required: false
      selector:
        number:
          min: 0
          max: 100000
          mode: box
